### ISSUE TITLE
Integer bug on temporalmixingqueue.js

### ISSUE THREAD

**Issue by Slater022** [reelyactive/barnowl#3]
Replace : 

let currentTime = new Date().getTime();
let nextTimeout = currentTime + instance.mixingDelayMilliseconds;

By : 

 let currentTime = Date.now();
 let nextTimeout =  currentTime + parseInt(instance.mixingDelayMilliseconds,10 );

In : temporalmixingqueue.js
To avoid string concatenation with instance.mixingDelayMilliseconds --> Generate error timeoverflow

**Comment by jeffyactive** [comment]
Thanks @Slater022, I didn't see you issue until now.  As long as the "mixingDelayMilliseconds" option is provided as a Number (i.e. Integer) then the code will work correctly.  Agreed that if that option is provided as a String, an error will occur.  Considering this as expected behaviour, but taking note to consider more explicit type checking in future.
